package game

import "sus-word-backend/internal/domain"

// DefaultWordList provides the curated word library grouped by categories.
var DefaultWordList = []domain.WordEntry{
	// Animals
	{Word: "Elephant", Category: "Animals"},
	{Word: "Penguin", Category: "Animals"},
	{Word: "Kangaroo", Category: "Animals"},
	{Word: "Dolphin", Category: "Animals"},
	{Word: "Giraffe", Category: "Animals"},
	{Word: "Cheetah", Category: "Animals"},
	{Word: "Octopus", Category: "Animals"},
	{Word: "Koala", Category: "Animals"},
	{Word: "Zebra", Category: "Animals"},
	{Word: "Panda", Category: "Animals"},
	{Word: "Chameleon", Category: "Animals"},
	{Word: "Flamingo", Category: "Animals"},
	{Word: "Gorilla", Category: "Animals"},
	{Word: "Hedgehog", Category: "Animals"},
	{Word: "Platypus", Category: "Animals"},

	// Food & Drink
	{Word: "Pizza", Category: "Food & Drink"},
	{Word: "Sushi", Category: "Food & Drink"},
	{Word: "Hamburger", Category: "Food & Drink"},
	{Word: "Spaghetti", Category: "Food & Drink"},
	{Word: "Taco", Category: "Food & Drink"},
	{Word: "Croissant", Category: "Food & Drink"},
	{Word: "Pancake", Category: "Food & Drink"},
	{Word: "Chocolate", Category: "Food & Drink"},
	{Word: "Ice Cream", Category: "Food & Drink"},
	{Word: "Popcorn", Category: "Food & Drink"},
	{Word: "Donut", Category: "Food & Drink"},
	{Word: "Burrito", Category: "Food & Drink"},
	{Word: "Waffle", Category: "Food & Drink"},
	{Word: "Espresso", Category: "Food & Drink"},
	{Word: "Smoothie", Category: "Food & Drink"},

	// Everyday Objects
	{Word: "Umbrella", Category: "Everyday Objects"},
	{Word: "Backpack", Category: "Everyday Objects"},
	{Word: "Headphones", Category: "Everyday Objects"},
	{Word: "Flashlight", Category: "Everyday Objects"},
	{Word: "Sunglasses", Category: "Everyday Objects"},
	{Word: "Toothbrush", Category: "Everyday Objects"},
	{Word: "Clock", Category: "Everyday Objects"},
	{Word: "Telescope", Category: "Everyday Objects"},
	{Word: "Compass", Category: "Everyday Objects"},
	{Word: "Notebook", Category: "Everyday Objects"},
	{Word: "Scissors", Category: "Everyday Objects"},
	{Word: "Wallet", Category: "Everyday Objects"},
	{Word: "Thermos", Category: "Everyday Objects"},
	{Word: "Guitar", Category: "Everyday Objects"},
	{Word: "Keyring", Category: "Everyday Objects"},

	// Places & Geography
	{Word: "Airport", Category: "Places"},
	{Word: "Library", Category: "Places"},
	{Word: "Museum", Category: "Places"},
	{Word: "Hospital", Category: "Places"},
	{Word: "Lighthouse", Category: "Places"},
	{Word: "Cinema", Category: "Places"},
	{Word: "Castle", Category: "Places"},
	{Word: "Submarine", Category: "Places"},
	{Word: "Volcano", Category: "Places"},
	{Word: "Amusement Park", Category: "Places"},
	{Word: "Train Station", Category: "Places"},
	{Word: "Bakery", Category: "Places"},
	{Word: "Aquarium", Category: "Places"},
	{Word: "Pyramid", Category: "Places"},
	{Word: "Observatory", Category: "Places"},

	// Sports & Leisure
	{Word: "Basketball", Category: "Sports & Leisure"},
	{Word: "Chess", Category: "Sports & Leisure"},
	{Word: "Tennis", Category: "Sports & Leisure"},
	{Word: "Snowboarding", Category: "Sports & Leisure"},
	{Word: "Archery", Category: "Sports & Leisure"},
	{Word: "Bowling", Category: "Sports & Leisure"},
	{Word: "Surfing", Category: "Sports & Leisure"},
	{Word: "Skateboarding", Category: "Sports & Leisure"},
	{Word: "Volleyball", Category: "Sports & Leisure"},
	{Word: "Rock Climbing", Category: "Sports & Leisure"},
	{Word: "Badminton", Category: "Sports & Leisure"},
	{Word: "Billiards", Category: "Sports & Leisure"},
	{Word: "Fencing", Category: "Sports & Leisure"},
	{Word: "Karate", Category: "Sports & Leisure"},
	{Word: "Marathon", Category: "Sports & Leisure"},

	// Technology
	{Word: "Smartphone", Category: "Technology"},
	{Word: "Drone", Category: "Technology"},
	{Word: "Satellite", Category: "Technology"},
	{Word: "Robot", Category: "Technology"},
	{Word: "Microscope", Category: "Technology"},
	{Word: "Laptop", Category: "Technology"},
	{Word: "3D Printer", Category: "Technology"},
	{Word: "Virtual Reality", Category: "Technology"},
	{Word: "Spaceship", Category: "Technology"},
	{Word: "Solar Panel", Category: "Technology"},
	{Word: "Electric Scooter", Category: "Technology"},
	{Word: "Smartwatch", Category: "Technology"},

	// Professions
	{Word: "Astronaut", Category: "Professions"},
	{Word: "Detective", Category: "Professions"},
	{Word: "Firefighter", Category: "Professions"},
	{Word: "Chef", Category: "Professions"},
	{Word: "Architect", Category: "Professions"},
	{Word: "Pilot", Category: "Professions"},
	{Word: "Magician", Category: "Professions"},
	{Word: "Surgeon", Category: "Professions"},
	{Word: "Photographer", Category: "Professions"},
	{Word: "Veterinarian", Category: "Professions"},
	{Word: "Archeologist", Category: "Professions"},
	{Word: "Scuba Diver", Category: "Professions"},

	// Nature & Weather
	{Word: "Rainbow", Category: "Nature & Weather"},
	{Word: "Avalanche", Category: "Nature & Weather"},
	{Word: "Waterfall", Category: "Nature & Weather"},
	{Word: "Tornado", Category: "Nature & Weather"},
	{Word: "Rainforest", Category: "Nature & Weather"},
	{Word: "Desert", Category: "Nature & Weather"},
	{Word: "Glacier", Category: "Nature & Weather"},
	{Word: "Lightning", Category: "Nature & Weather"},
	{Word: "Northern Lights", Category: "Nature & Weather"},
	{Word: "Meteor Shower", Category: "Nature & Weather"},
}
